### ISSUE TITLE
Foil cards feature

### ISSUE THREAD

**Issue by Refloow** [Refloow/Steam-Card-Bot-PRO#12]
Add option to buy and sell foil cards with the bot.

**Comment by dk992** [comment]
when will we get it ?

**Comment by dk992** [comment]
any ETA ?

**Comment by Refloow** [comment]
> any ETA ?

Next update which i will be working on soon, feel free to join our discord server where we post announcements and info about the updates.

[Discord](https://discord.gg/D8WCtDD)

We push updates based on donations and stars activity on the project:

[Leave an Star](https://github.com/OSL-Works/Steam-Card-Bot-PRO)
[Donate](https://steamcommunity.com/tradeoffer/new/?partner=392773011&token=CncehZti)
