### ISSUE TITLE
[Suggestion] Add individual card buying/selling

### ISSUE THREAD

**Issue by CrustTF2** [Refloow/Steam-Card-Bot-PRO#37]
Just a suggestion, but the bots should be able to buy and sell individual cards, for let's say refined metal.

People are normally buying trading cards anywhere from 0.22-0.55 refined each (2 scrap - 1 reclaimed, 2 scrap), so why can't the bots?

**Comment by Refloow** [comment]
Level up Bots don't sell cards for the sake of selling cards. Its not in any sellers interes to sell you cards which would leave him with incomplete sets. Even tho you would need certain cards to complete your sets, you can obtain them other way and complete your sets with 1:1 trading services ones you have duplicates. There is option to buy/sell complete sets one at the time for gems/ref metal.

What you are talking about is not suggestion for a card bot rather a concept for cards, emoticons and backgrounds buying and selling bot.
This project will be released for free one day, but i cant promise when, you could order/buy early access version.
If you want more details feel free to contact me on discord
MajokingGames#4996
