### ISSUE TITLE
Error,i don't know how to solve it

### ISSUE THREAD

**Issue by Patr1ck-233** [Refloow/Steam-Card-Bot-PRO#43]
Error,i don't know how to solve it
![屏幕截图 2022-02-11 024531](https://user-images.githubusercontent.com/99354599/153478338-567f0ba2-442f-4260-82b9-2f36ab8fc1f3.png)

**Comment by Patr1ck-233** [comment]
The last line says "Press any key to continue"

**Comment by Refloow** [comment]
Seems like you configured something wrong. Try installing again and filling out config.js right
